# chunker: default program

In [1]:
from default import *
import os

ModuleNotFoundError: No module named 'default'

## Run the default solution on dev

In [2]:
chunker = LSTMTagger(os.path.join('../data', 'train.txt.gz'), os.path.join('../data', 'chunker'), '.tar')
decoder_output = chunker.decode('../data/input/dev.txt')
print(chunker.model)

OSError: Error: missing model file ../data/chunker.tar

## Evaluate the default output

In [15]:
import string
all_character = string.printable
print(all_character[17])

h


In [1]:
import torch

v1 = torch.zeros((1, 100))
v2 = torch.zeros((1, 100))
v3 = torch.zeros((1, 100))
print(v1.shape)
# print(torch.cat([v1, v2, v3]).shape)

torch.Size([1, 100])


In [6]:
idx=[]
# idx.append(v1)
# idx.append(v2)
# idx.append(v3)
v4 = torch.cat([v1, v2, v3])
v5 = v4.view(1, -1)
print(v5.shape)

torch.Size([1, 300])


In [5]:
import torch
torch.zeros([len(string.printable)])
v1 = torch.zeros(1, 3)
v2 = torch.zeros(1, 3)
v3 = torch.zeros(1, 3)
v1[0,1] = 1
v2[0, 0] = 18
v3[0, 2] = 1
print(torch.cat([v1, v2, v3]).shape)

torch.Size([3, 3])


In [15]:
mydict = {'george':16,'amber':19}
print(list(mydict.keys())[list(mydict.values()).index(16)])

george


In [12]:
print(len(sentence))

3


In [10]:
import torch.nn as nn
word_embeddings = nn.Embedding(50, 128)
sentence = torch.tensor([1, 3, 4], dtype=torch.long)
embeds = word_embeddings(sentence)

lstm = nn.LSTM(128, 64, bidirectional=False)
lstm_out, _ = lstm(embeds.view(len(sentence), 1, -1))
a = embeds.view(len(sentence), 1, -1)

In [ ]:
lstm = nn.LSTM(128, 64, bidirectional=False)
elf.hidden2tag = nn.Linear(hidden_dim, tagset_size)

In [11]:
embeds.shape

torch.Size([3, 128])

In [3]:
flat_output = [ output for sent in decoder_output for output in sent ]
import conlleval
true_seqs = []
with open(os.path.join('../data','reference','dev.out')) as r:
    for sent in conlleval.read_file(r):
        true_seqs += sent.split()
conlleval.evaluate(true_seqs, flat_output)

processed 23663 tokens with 11896 phrases; found: 12029 phrases; correct: 9151.
accuracy:  86.49%; (non-O)
accuracy:  87.59%; precision:  76.07%; recall:  76.93%; FB1:  76.50
             ADJP: precision:  44.71%; recall:  16.81%; FB1:  24.44  85
             ADVP: precision:  70.49%; recall:  43.22%; FB1:  53.58  244
            CONJP: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
             INTJ: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
               NP: precision:  74.74%; recall:  79.94%; FB1:  77.25  6671
               PP: precision:  91.22%; recall:  88.49%; FB1:  89.83  2368
              PRT: precision:  67.44%; recall:  64.44%; FB1:  65.91  43
             SBAR: precision:  82.09%; recall:  46.41%; FB1:  59.30  134
               VP: precision:  66.67%; recall:  71.88%; FB1:  69.17  2484


(76.07448665724499, 76.9250168123739, 76.49738766980145)

## Documentation

Write some beautiful documentation of your program here.

1. try with other 2 methods
2. unknown words (misspelling --> unk )

In [1]:
from chunker_2rnn import *
import os

In [5]:
dic = {'aa':0, 'bb':1, 'cc':2, 'dd':4}
print('aa' in dic.keys())

True


In [5]:
chunker = LSTMTagger(os.path.join('../data', 'train.txt.gz'), os.path.join('../data', 'chunker'), '.tar')
print(chunker.word_to_ix)

{'[unk]': 0, 'in': 1, 'the': 2, 'pound': 3, 'is': 4, 'widely': 5, 'expected': 6, 'to': 7, 'take': 8, 'another': 9, 'sharp': 10, 'dive': 11, 'if': 12, 'trade': 13, 'figures': 14, 'for': 15, 'september': 16, ',': 17, 'due': 18, 'release': 19, 'tomorrow': 20, 'fail': 21, 'show': 22, 'a': 23, 'substantial': 24, 'improvement': 25, 'from': 26, 'july': 27, 'and': 28, 'august': 29, "'s": 30, 'near-record': 31, '.': 32, 'chancellor': 33, 'of': 34, 'exchequer': 35, 'nigel': 36, 'lawson': 37, 'restated': 38, 'commitment': 39, 'firm': 40, 'monetary': 41, 'policy': 42, 'has': 43, 'helped': 44, 'prevent': 45, 'sterling': 46, 'over': 47, 'past': 48, 'week': 49, 'but': 50, 'analysts': 51, 'underlying': 52, 'support': 53, 'been': 54, 'eroded': 55, 'by': 56, 'failure': 57, 'announce': 58, 'any': 59, 'new': 60, 'measures': 61, 'his': 62, 'mansion': 63, 'house': 64, 'speech': 65, 'last': 66, 'thursday': 67, 'this': 68, 'increased': 69, 'risk': 70, 'government': 71, 'being': 72, 'forced': 73, 'increase': 7

In [2]:
chunker = LSTMTagger(os.path.join('../data', 'train.txt.gz'), os.path.join('../data', 'chunker'), '.tar')
# chunker.train_1()
# chunker.train_2()
chunker.train()
decoder_output = chunker.decode('../data/input/dev.txt')
print(chunker.model)

100%|██████████| 8936/8936 [03:21<00:00, 44.40it/s]
saving model file: ../data/chunker0.tar
100%|██████████| 8936/8936 [02:36<00:00, 57.20it/s]
saving model file: ../data/chunker1.tar
100%|██████████| 8936/8936 [03:12<00:00, 46.48it/s]
saving model file: ../data/chunker2.tar
100%|██████████| 8936/8936 [03:16<00:00, 45.44it/s] 
saving model file: ../data/chunker3.tar
100%|██████████| 8936/8936 [03:33<00:00, 41.83it/s]
saving model file: ../data/chunker4.tar
100%|██████████| 8936/8936 [03:40<00:00, 40.61it/s]
saving model file: ../data/chunker5.tar
100%|██████████| 8936/8936 [02:58<00:00, 50.04it/s]
saving model file: ../data/chunker6.tar
100%|██████████| 8936/8936 [02:59<00:00, 49.84it/s] 
saving model file: ../data/chunker7.tar
100%|██████████| 8936/8936 [03:22<00:00, 44.17it/s]
saving model file: ../data/chunker8.tar
100%|██████████| 8936/8936 [03:22<00:00, 44.20it/s]
saving model file: ../data/chunker.tar
100%|██████████| 1027/1027 [00:04<00:00, 252.53it/s]

LSTMTaggerModel(
  (word_embeddings): Embedding(9675, 128)
  (lstm_character): LSTM(300, 150)
  (lstm_chunker): LSTM(278, 64)
  (hidden2tag): Linear(in_features=64, out_features=22, bias=True)
)


In [4]:
print(chunker.training_data[0])

(('[UNK]', 'in', 'the', 'pound', 'is', 'widely', 'expected', 'to', 'take', 'another', 'sharp', 'dive', 'if', 'trade', 'figures', 'for', 'September', ',', 'due', 'for', 'release', 'tomorrow', ',', 'fail', 'to', 'show', 'a', 'substantial', 'improvement', 'from', 'July', 'and', 'August', "'s", 'near-record', '[UNK]', '.'), ('B-NP', 'B-PP', 'B-NP', 'I-NP', 'B-VP', 'I-VP', 'I-VP', 'I-VP', 'I-VP', 'B-NP', 'I-NP', 'I-NP', 'B-SBAR', 'B-NP', 'I-NP', 'B-PP', 'B-NP', 'O', 'B-ADJP', 'B-PP', 'B-NP', 'B-NP', 'O', 'B-VP', 'I-VP', 'I-VP', 'B-NP', 'I-NP', 'I-NP', 'B-PP', 'B-NP', 'I-NP', 'I-NP', 'B-NP', 'I-NP', 'I-NP', 'O'), ('NN', 'IN', 'DT', 'NN', 'VBZ', 'RB', 'VBN', 'TO', 'VB', 'DT', 'JJ', 'NN', 'IN', 'NN', 'NNS', 'IN', 'NNP', ',', 'JJ', 'IN', 'NN', 'NN', ',', 'VB', 'TO', 'VB', 'DT', 'JJ', 'NN', 'IN', 'NNP', 'CC', 'NNP', 'POS', 'JJ', 'NNS', '.'))


In [6]:
a = 'advd'
for i in range(len(a)):
    print(a[i])

a
d
v
d


In [67]:
def sc_encoding(sentence, word_to_ix):
    sentence_sc_vectors = list()
    for ix in sentence:
        word = list(word_to_ix.keys())[list(word_to_ix.values()).index(ix)]
        v1 = torch.zeros(1, len(string.printable))
        v2 = torch.zeros(1, len(string.printable))
        v3 = torch.zeros(1, len(string.printable))
        for i in range(len(word)):
            if word[i] not in string.printable:
                continue
            if i == 0:
                v1[0, string.printable.index(word[i])] = 1
            elif i == len(word) - 1:
                v3[0, string.printable.index(word[i])] = 1
            else:
                v2[0, string.printable.index(word[i])] += 1
        sentence_sc_vectors.append(torch.cat([v1, v2, v3], -1))
    return torch.stack(sentence_sc_vectors)

In [75]:
b = sc_encoding([0, 1, 2], {'apple': 0, 'peach': 1, 'passion': 2})
b.shape

torch.Size([3, 1, 128])

In [78]:
a

tensor([[[ 1.4966, -0.2824,  0.1033,  1.3489, -0.4910, -1.4463, -0.3246,
           1.0076,  0.7639,  0.6210,  0.5014,  0.8068, -0.5439, -0.2901,
          -0.6537,  1.4458,  0.6221,  0.5799,  2.3840, -0.3536, -0.7793,
          -0.0761,  1.7470,  0.8444, -0.5730, -0.3621, -0.6711,  2.7271,
          -0.9161,  1.8098, -0.0633, -0.0111, -0.0579, -1.4607,  0.0806,
          -0.5276, -0.8619,  0.0411, -0.6323,  0.0357, -0.6074, -1.5623,
          -0.8302,  1.4546,  0.1733,  0.0871, -0.5880, -1.0189,  0.4940,
           1.3168,  0.1132, -0.0419, -0.3541,  0.5370, -0.4878,  0.4518,
           0.7325, -1.5575,  0.5028, -0.1080, -0.0144, -0.3255,  0.3273,
           0.9974, -1.1979, -0.3156,  2.0540, -1.5374,  0.2804, -1.1135,
          -0.7010, -1.6471,  0.9381,  0.2423,  0.3513,  0.9856, -0.1453,
           0.3481, -0.1859, -0.4689,  1.0155,  0.2517, -0.8997,  0.2634,
           2.4138, -0.9014,  1.8924, -0.6188,  1.1485, -1.2377,  0.8898,
          -0.7355, -0.1930,  0.7282, -0.6860, -0.85

In [79]:
b

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 1., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.

In [91]:
c = torch.cat((a, b), -1)
c[0, 0][128:]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 2.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 

In [94]:
b[0, 0] == c[0, 0][128:]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

## Analysis

Do some analysis of the results. What ideas did you try? What worked and what did not?